export enum EActivityLevel {
  SEDENTARY = "SEDENTARY",
  LIGHTLY_EXERCISE = "LIGHTLY_EXERCISE",
  MODERATELY_EXERCISE = "MODERATELY_EXERCISE",
  HEAVY_EXERCISE = "HEAVY_EXERCISE",
  ATHLETE = "ATHLETE",
}
